### ISSUE TITLE
CloudEvent data in Array format throws a ValidationError

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#280]
**Describe the Bug**

When creating or receiving a `CloudEvent`, if the data is in the form of an Array - which is valid JSON - we get a validation error.

**Steps to Reproduce**
1. use `new CloudEvent()` to create an event with the `data` property as an array. For example:

```js
const ce = new CloudEvent({ source: '/test', type: 'example', data: [ 1, 2, 3 ] });
```
That will produce:

```
   TypeError: invalid payload
      at Object.validateV1 (src/event/spec.ts:14:11)
      at CloudEvent.validate (src/event/cloudevent.ts:178:16)
      at new CloudEvent (src/event/cloudevent.ts:121:10)
```

**Expected Behavior**

No error thrown.

**Additional context**

The schema seems to have wrongly typed data here https://github.com/cloudevents/sdk-javascript/blob/master/src/event/schemas.ts#L12-L14 and here https://github.com/cloudevents/sdk-javascript/blob/master/src/event/schemas.ts#L91-L93

**Comment by lance** [comment]
Although the schema has not changed, in previous versions the event was (in most cases) validated on demand. With the new version, you are not allowed to create an invalid event. In this case, the event is not invalid, but the schema thinks it is.

**Comment by lance** [comment]
The fix for this also adds tests for `boolean` and `null` which are also valid JSON.
