### ISSUE TITLE
Issue converting a golang cloudevents type Kafka message

### ISSUE THREAD

**Issue by dqiubread** [cloudevents/sdk-javascript#506]
Hello,
I'm trying to deserialize a kafka message that was initially creating using the cloudevents type in golang. An error occurs when i try to deserialize the kafka message to a cloudevent type.
``` 
const val = HTTP.toEvent({
        headers: message.headers,
        body: message.value
      });
``` 
Error message I get:
```
   From Node.js Internals:
    TypeError: contentType.startsWith is not a function
      at getMode (/Users/davidqiu/Documents/GIT_Repos/breadplatform/platform-ui-tests/node_modules/cloudevents/dist/message/http/index.js:102:26)
      at Object.deserialize [as toEvent] (/Users/davidqiu/Documents/GIT_Repos/breadplatform/platform-ui-tests/node_modules/cloudevents/dist/message/http/index.js:80:19)
      at <unknown> (/Users/davidqiu/Documents/GIT_Repos/breadplatform/platform-ui-tests/cypress/plugins/kafkaIntegrationPlugin.js:64:25)
      at <unknown> (/Users/davidqiu/Documents/GIT_Repos/breadplatform/platform-ui-tests/cypress/plugins/kafkaIntegrationPlugin.js:233:35)
    at Array.forEach (<anonymous>)
      at <unknown> (/Users/davidqiu/Documents/GIT_Repos/breadplatform/platform-ui-tests/cypress/plugins/kafkaIntegrationPlugin.js:231:34)
```

**Comment by lance** [comment]
Hi @dqiubread when you are deserializing a Kafka message, you should use the Kafka message protocol in this module. Can you please try something like this and see if that resolves your issue?

```
const { Message, Kafka, KafkaMessage, KafkaEvent } = require('cloudevents');
const event = Kafka.toEvent( { headers: message.headers, body: message.value });
```

**Comment by lance** [comment]
Closing this, assuming this worked for you @dqiubread. Please reopen with more detail if not.
